stages:
  - build
unbound-importer:
  stage: build
  image: docker:19.03.12
  services:
    - docker:dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build -f importer/Dockerfile --build-arg GIT_VERSION="$CI_PROJECT_NAME-$CI_PIPELINE_IID" --tag $CI_REGISTRY_IMAGE/importer-$CI_COMMIT_BRANCH importer
    - docker push $CI_REGISTRY_IMAGE/importer-$CI_COMMIT_BRANCH:latest
  when: manual
