stages:
  - build

opnsense-unbound-inporter:
  stage: build
  image: docker:19.03.12
  services:
    - docker:19.03.12-dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build --build-arg GIT_VERSION="$CI_PROJECT_NAME-$CI_PIPELINE_IID" --tag $CI_REGISTRY_IMAGE/opnsense-unbound-inporter-$CI_COMMIT_BRANCH
    - docker push $CI_REGISTRY_IMAGE/opnsense-unbound-inporter-$CI_COMMIT_BRANCH:latest
  when: manual
